### ISSUE TITLE
1 More than 1 boss can be present at any time.

### ISSUE THREAD

**Issue by higps** [higps/robogithub#37]
There should not be possible to select a boss if someone is a boss  already.

**Comment by eisbaer66** [comment]
i guess you want this to be a general rule for robots of role "ZBOSS"?
or should each robot be able to define some kind of pool, where you can only create one robot per pool?
so all bosses would assign themself to the pool named "Bosses" (as part of the `AddRobot(...)`-call) to allow only one of them at the same time.
would make for a more flexible system, but you would have to remember to assign any new boss-robot to the pool, too 😉 

i guess we could have this flexible system in the background, but assign all robots of role "ZBOSS" to the same pool automatically. this would allow more pools in the future, but makes zbosses less error prone 😄

**Comment by higps** [comment]
We should assign robots to pools, perhaps specify to subclass or class, then some dynamic way of adjusting the limitation, to either use player count amount or static amount
